### ISSUE TITLE
UV degradation of polymers

### ISSUE THREAD

**Issue by joymcjoy** [TheoryDivision/covid19_biosafety_cabinet#3]
Hi, thank you for your work
It was exactly what I have been looking for as I am building a UV-C disinfectant my self.
Addressing also the issue of turning mask by placing a bulb under a fine mesh (special glass is not available in a short time) and one above (on the lid).
What I am worried about when applying UV-C disinfection to polymers (the micro blown fabric of masks is a polypropylene) is the degradation of polymer bonds as it is the exact same chemical reaction that destroys DNA, RNA.
This will result in degradation of filtering of the mask and even worse maybe generate fine dust of broken polymers which the wearer of the mask would inhale when using them.
Have you any considerations about that? 
I will try to calculate to what amount the energy levels you observed to disinfect are comparable to sun exposures as there are figures of degradation in the sun.
Keep up the work and your health

**Comment by emilydolson** [comment]
That's a great question!

In the pre-print we suggest that mask degradation is indeed most likely the limiting factor here. We haven't done any tests on it ourselves, but there's some great data in these papers: https://www.tandfonline.com/doi/full/10.1080/15459624.2015.1018518 and https://academic.oup.com/annweh/article/56/1/92/166111. While the first one shows that masks do indeed break down, the second one shows that three cycles of UVGI decontamination (as we recommend in the paper) is safe. That paper also delivered what I believe is a substantially higher dose (the other authors are double-checking my unit conversion, there) of UVGI than we are suggesting, so it should translate to our recommendations.

It is worth considering the fact that there's a trade-off between being sure that all pathogens have been inactivated and preventing mask degradation. The recommendation we give here is designed to be *very* conservative with regard to ensuring that all pathogens are dead. That comes at the cost of potentially accelerating mask degradation. Depending on conditions in individual hospitals, it may be worth striking a different balance, but we don't have enough data on mask degradation to give a clear guideline.

One relatively safe way to cut down on mask degradation would be to do the same measurements that we did on your biosafety cabinet. That way, instead of using our worst-case recommendation, you can use numbers tailored specifically to your cabinet. Of course that depends on having a way to measure UV levels (either a UV meter or a photodiode set-up like we used here).

Good idea to compare against what we know about sun degradation. One thing to be slightly cautious of there is that biosafety cabinets have a much higher amount of UV-C radiation than the sun does (we were actually originally hoping to use sunlight for decontamination, but it turns out UV-C radiation is important for killing viruses like sars-cov-2). I'm not sure what effect that has on mask degradation, but it's something to be aware of.

**Comment by emilydolson** [comment]
Update: we have fleshed out our literature review/calculations on UV degradation of polymers in the latest version of the PDF. The primary takeaway is that based on the literature it appears that up to 40 cycles of decontamination at the level we recommend should be very safe,  and even more are likely to be okay (although masks would probably break down due to normal wear and tear well before reaching that point). 

That said, some colleagues raised a concern that UV radiation may interfere with fixed electrostatic charges in the fabric of N95s (used for filtering fine aerosols), on the grounds that this appears to be an issue with ionizing gamma radiation. We are working with them to test whether the same issue results from our protocol and hope to have data this week.

**Comment by emilydolson** [comment]
Our colleagues have completed their tests and found no evidence of degradation after 6 hours in a biosafety cabinet. We have added their data to the manuscript. I'm going to go ahead and close this issue, but feel free to let us know if you have further questions!
